### ISSUE TITLE
PHP Fatal error:  Cannot use oat\taoQtiItem\model\qti\Object as Object because 'Object' is a special class name in /taoQtiItem/model/qti/ParserFactory.php on line 54

### ISSUE THREAD

**Issue by gunturaf** [oat-sa/extension-tao-itemqti#1104]
I don't know if anyone ever encounter this or is it just me but
when I tried to save changes after adding and updating elements of Items
this issue happened on cPanel with PHP 7 at file `/model/qti/ParserFactory.php`

I managed to handle the error by modifying line 54 from:

`use oat\taoQtiItem\model\qti\Object;`

to this:

`use oat\taoQtiItem\model\qti\Object as QtiObject;`

and modify line 1383 from:

`$returnValue = new Object($attributes);`

to:

`$returnValue = new QtiObject($attributes);`

I'm happy to fill a PR if this issue is confirmed.

**Comment by krampstudio** [comment]
Thanks for the report! 
Could you please give us your exact PHP version. 
And yes any contribution is more than welcomed. 
If you create a PR, please do it against the `develop` branch not the `master` branch.

**Comment by ionutpad** [comment]
I guess you are using php 7.2. Since this version the new typehint object was introduced https://wiki.php.net/rfc/object-typehint.

**Comment by gunturaf** [comment]
@krampstudio @ionutpad sorry for the late response, yes it was PHP 7.2 which installed in my cPanel

**Comment by ionutpad** [comment]
I recommend using PHP less than 7.2. Also you can submit the PR to fix this.
We are going to work to support PHP 7.2 in the future.
Cheers :)

**Comment by mrft** [comment]
Might be useful to check whether the php version is supported during the requirements check of the install procedure...
